Add support for Novaseq X Plus
Molmed/summary-report-development pull request #51
Opened 2023-06-14 11:16 UTC by matrulda

Changes in this PR:
- Added RunParameters tags for NovaSeq X Plus
- Added NovaSeq X Plus RunParameters file + unit test
- Updated the interop version we use to be compatible with NovaSeq X Plus
- Updated key search script so that keys in lists can be found
- Updated other python packages for security and dependecy reasons

2023-06-15 08:33 UTC, b97pla requested changes
:+1: looks good, I only had one comment.

2023-06-15 08:33 UTC, b97pla commented on bin/get_metadata.py
> +                    yield from self.find(i, tag)
I think you should add a conditional at the top of this function to ensure that `d` is a `dict`. This construct feeds anything from a list into the function and if it's not a dict, it will throw an exception at e.g. line 35 or 36.

2023-06-15 10:43 UTC, matrulda commented on bin/get_metadata.py
> +                    yield from self.find(i, tag)
Good catch, will fix!

2023-06-21 08:20 UTC, b97pla approved these changes
:+1: Great work!

2023-06-21 08:21 UTC, merged